name: Build latest app
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Create executable archive
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install --no-dev
      - name: Download phar builder
        run: wget https://github.com/clue/phar-composer/releases/download/v1.3.0/phar-composer-1.3.0.phar -O phar-composer.phar
      - name: Create PHAR
        run: php -d phar.readonly=off phar-composer.phar build . gog-downloader.phar
      - name: Rename
        run: mv gog-downloader.phar gog-downloader
      - name: Create artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: gog-downloader
          path: gog-downloader
